version: '3.8'

services:
  api:
    image: ${DOCKER_USERNAME}/frp-manager-api:latest
    # build: .
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
      - ./configs:/app/configs
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/frp_manager.db
      - SECRET_KEY=${SECRET_KEY}
      - WHMCS_API_URL=${WHMCS_API_URL}
      - WHMCS_IDENTIFIER=${WHMCS_IDENTIFIER}
      - WHMCS_SECRET=${WHMCS_SECRET}
      - API_URL=http://localhost:8000
    command: python main.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  manager:
    build: .
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
      - ./configs:/app/configs
    environment:
      - API_URL=http://api:8000
    command: manage
    depends_on:
      - api

  # 如果需要使用MySQL替代SQLite，取消下面的注释
  # db:
  #   image: mysql:8.0
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_DATABASE=frp_manager
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   restart: unless-stopped

# volumes:
#   mysql_data:
